modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/sepals/issues"
license = "GPLv3"

[[mods]]
modId = "sepals"
version = "${version}"
displayName = "Sepals"
authors = "cao_awa"
description = '''
Sepals is an extremely radical and experimental optimization for Minecraft server performances.
'''
#logoFile = ""

[[dependencies.sepals]]
modId = "neoforge"
type = "required"
versionRange = "[21.4.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sepals]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sepals]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sepals.mixins.json"
